/**
 * Mitl-ufer public API
 * This is the public API of Mitl-ufer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tobrohl@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MitlUferPublicApi) {
      root.MitlUferPublicApi = {};
    }
    root.MitlUferPublicApi.User = factory(root.MitlUferPublicApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The User model module.
   * @module model/User
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   * @param name {String} 
   * @param laufort {String} 
   * @param eMail {String} 
   * @param geburtsdatum {Date} 
   * @param laufniveau {module:model/User.LaufniveauEnum} 
   * @param ziel {Number} 
   * @param profilbild {String} 
   */
  var exports = function(name, laufort, eMail, geburtsdatum, laufniveau, ziel, profilbild) {
    var _this = this;

    _this['name'] = name;
    _this['laufort'] = laufort;
    _this['eMail'] = eMail;
    _this['geburtsdatum'] = geburtsdatum;
    _this['laufniveau'] = laufniveau;
    _this['ziel'] = ziel;
    _this['profilbild'] = profilbild;
  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('laufort')) {
        obj['laufort'] = ApiClient.convertToType(data['laufort'], 'String');
      }
      if (data.hasOwnProperty('eMail')) {
        obj['eMail'] = ApiClient.convertToType(data['eMail'], 'String');
      }
      if (data.hasOwnProperty('geburtsdatum')) {
        obj['geburtsdatum'] = ApiClient.convertToType(data['geburtsdatum'], 'Date');
      }
      if (data.hasOwnProperty('laufniveau')) {
        obj['laufniveau'] = ApiClient.convertToType(data['laufniveau'], 'String');
      }
      if (data.hasOwnProperty('ziel')) {
        obj['ziel'] = ApiClient.convertToType(data['ziel'], 'Number');
      }
      if (data.hasOwnProperty('profilbild')) {
        obj['profilbild'] = ApiClient.convertToType(data['profilbild'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} laufort
   */
  exports.prototype['laufort'] = undefined;
  /**
   * @member {String} eMail
   */
  exports.prototype['eMail'] = undefined;
  /**
   * @member {Date} geburtsdatum
   */
  exports.prototype['geburtsdatum'] = undefined;
  /**
   * @member {module:model/User.LaufniveauEnum} laufniveau
   */
  exports.prototype['laufniveau'] = undefined;
  /**
   * @member {Number} ziel
   */
  exports.prototype['ziel'] = undefined;
  /**
   * @member {String} profilbild
   */
  exports.prototype['profilbild'] = undefined;


  /**
   * Allowed values for the <code>laufniveau</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LaufniveauEnum = {
    /**
     * value: "Anfaenger"
     * @const
     */
    "Anfaenger": "Anfaenger",
    /**
     * value: "Fortgeschritten"
     * @const
     */
    "Fortgeschritten": "Fortgeschritten",
    /**
     * value: "Profi"
     * @const
     */
    "Profi": "Profi"  };


  return exports;
}));


